jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing clang
          command: 'apt-get update && apt-get install -y clang && clang --version'
      - run:
          name: Installing cmake
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Building debug
          command: 'cd Generated && make config=debug'
      - run:
          name: Building release
          command: 'cd Generated && make config=release'
